%% Author: Igor compiler
%% Compiler version: igorc 2.1.3
%% DO NOT EDIT THIS FILE - it is machine generated

-record(hello, {
}).

-record(game_category_created, {
    data :: web_protocol:game_category_excerpt()
}).

-record(game_category_updated, {
    data :: web_protocol:game_category_excerpt()
}).

-record(game_category_deleted, {
    data :: web_protocol:game_category_excerpt()
}).

-record(game_item_updated, {
    data :: web_protocol:game_item()
}).

