%% Author: Igor compiler
%% Compiler version: igorc 2.1.0
%% DO NOT EDIT THIS FILE - it is machine generated

-record(stripe_list, {
    object = <<"list">> :: binary(),
    url :: binary() | 'undefined',
    has_more :: boolean(),
    data :: [_T]
}).

-record(funds, {
    currency :: binary(),
    amount :: igor_types:int(),
    source_types :: igor_types:dict(binary(), igor_types:int())
}).

-record(balance, {
    object = <<"balance">> :: binary(),
    available :: [stripe_protocol:funds()],
    connect_reserved :: [stripe_protocol:funds()] | 'undefined',
    livemode :: boolean(),
    pending :: [stripe_protocol:funds()]
}).

-record(customer, {
    id :: binary(),
    object = <<"customer">> :: binary()
}).

-record(charge, {
    id :: binary(),
    object = <<"charge">> :: binary(),
    amount :: igor_types:uint(),
    amount_refunded :: igor_types:uint(),
    application :: binary() | 'undefined',
    application_fee :: binary() | 'undefined',
    balance_transaction :: binary() | 'undefined',
    captured :: boolean(),
    created :: igor_types:uint(),
    currency :: binary() | 'undefined',
    customer :: binary() | 'undefined',
    description :: binary() | 'undefined',
    destination :: binary() | 'undefined',
    dispute :: binary() | 'undefined',
    failure_code :: binary() | 'undefined',
    failure_message :: binary() | 'undefined',
    invoice :: binary() | 'undefined',
    livemode :: boolean(),
    on_behalf_of :: binary() | 'undefined',
    order :: binary() | 'undefined',
    paid :: boolean(),
    receipt_email :: binary() | 'undefined',
    receipt_number :: binary() | 'undefined',
    refunded :: boolean(),
    review :: binary() | 'undefined',
    source_transfer :: binary() | 'undefined',
    statement_descriptor :: binary() | 'undefined',
    status :: stripe_protocol:charge_status(),
    transfer :: binary() | 'undefined',
    transfer_group :: binary() | 'undefined'
}).

-record(create_customer_request, {
    email :: binary(),
    source :: binary(),
    description :: binary()
}).

-record(create_charge_request, {
    amount :: igor_types:int(),
    currency :: binary(),
    description :: binary(),
    source :: binary() | 'undefined',
    customer :: binary() | 'undefined'
}).

